-- AI Agents enhancement
ALTER TABLE agents ADD COLUMN IF NOT EXISTS knowledge_base_files TEXT[] DEFAULT '{}';
ALTER TABLE agents ADD COLUMN IF NOT EXISTS strategy_focus TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;

-- Agent Knowledge Files
CREATE TABLE IF NOT EXISTS agent_knowledge_files (
  id BIGSERIAL PRIMARY KEY,
  agent_id BIGINT REFERENCES agents(id) ON DELETE CASCADE,
  filename VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  file_size BIGINT,
  content_type VARCHAR(100),
  uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Update tenants to include assigned agent
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS assigned_agent_id BIGINT REFERENCES agents(id);

-- Government plan analysis
CREATE TABLE IF NOT EXISTS government_plans (
  id BIGSERIAL PRIMARY KEY,
  tenant_id BIGINT REFERENCES tenants(id),
  filename VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  strategic_axes JSONB,
  processed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Action plans generated by agents
CREATE TABLE IF NOT EXISTS action_plans (
  id BIGSERIAL PRIMARY KEY,
  tenant_id BIGINT REFERENCES tenants(id),
  agent_id BIGINT REFERENCES agents(id),
  core_values JSONB,
  communication_profile JSONB,
  tactical_actions JSONB,
  generated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_agent_knowledge_files_agent_id ON agent_knowledge_files(agent_id);
CREATE INDEX IF NOT EXISTS idx_tenants_assigned_agent_id ON tenants(assigned_agent_id);
CREATE INDEX IF NOT EXISTS idx_government_plans_tenant_id ON government_plans(tenant_id);
CREATE INDEX IF NOT EXISTS idx_action_plans_tenant_id ON action_plans(tenant_id);
CREATE INDEX IF NOT EXISTS idx_action_plans_agent_id ON action_plans(agent_id);